#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6443694484                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : cn                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://itunes.apple.com/app/id6443694484                                         # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : 购物小抄                                            # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : 购物小抄 - 可以和家人朋友分享的购物清单APP

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Swallow Works Studio                            
your_link                                 : http://tiantianjizhang.swalloworkstudio.com                     
your_city                                 : Tokyo                                
email_address                             : swalloworks@gmail.com
facebook_username                         : mainichishoppinglist                                          
instagram_username                        : 
twitter_username                          : swalloworks
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : 可与家人朋友分享购物清单
    description                           : 清单内容的更新会即时同步到每一个共享成员。即使大家分开购物，也可以看到彼此进度，不会重复购买相同的东西。
    fontawesome_icon_name                 : magic
    
  - title                                 : 商品自动推荐
    description                           : 输入商品名时，APP会搜索购买记录和人气商品，自动显示相关商品以供选择。
    fontawesome_icon_name                 : heartbeat
  
  - title                                 : 可记录数量，价格
    description                           : 如果有输入数量，价格，清单会自动计算总金额
    fontawesome_icon_name                 : sync

  - title                                 : 本机优先
    description                           : 所有资料都会先储存在本机。即使您没有连网，也可以查看或编辑清单内容。
    fontawesome_icon_name                 : bell

  - title                                 : 安全
    description                           : 数据是您的。即使是开发者，也无法查看您的数据。
    fontawesome_icon_name                 : star

  - title                                 : 无需登录账号
    description                           : 自动绑定AppleID帐号, 无需登录就可以使用
    fontawesome_icon_name                 : adjust



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff" 
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
